apiVersion: v1
kind: Service
metadata:
  name: nodered-worker-service
spec:
  ports:
  - port: 18080
    name: jobctl
    protocol: TCP
    targetPort: 1888
  - port: 18082
    name: task
    protocol: TCP
    targetPort: 1880
  selector:
    app: nodered-worker
  type: LoadBalancer