apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered-worker
  template:
    metadata:
      labels:
        app: nodered-worker
    spec:
      containers:
      - name: nodered-worker-server
        env:
          - name: SERVICENAME
            value: nodered-service
          - name: CLUSTER_GROUP
            value: default
          - name: TOPICS
            value: topic1,topic2,git
          - name: FLOW_MAX
            value: "1"
        image: worker
        imagePullPolicy: Never # ローカルにあるイメージを使う
        ports:
        - containerPort: 1888
        resources:
          limits:
            cpu: 500m
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
          - mountPath: /data
            name: nodered-data-store-volume
      volumes:
        - name: nodered-data-store-volume
          persistentVolumeClaim:
            claimName: nodered-data-pvc