apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-workspace-pvc
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-data-pvc
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-output-pvc
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---