apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/C/devs/kubernetes-nodered/PersistentVolume/"
