apiVersion: v1
kind: Service
metadata:
  name: sshd-service
spec:
  selector:
    app: sshd
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2222
    targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: ssh-passwd
        # securityContext:
        #   privileged: false
        #   runAsUser: 1000
        image: nojaja/eg_sshd:latest
        imagePullPolicy: Never
        volumeMounts:
          - name: nodered-data-store-volume
            mountPath: /data
          - name: nodered-workspace-volume
            mountPath: /workspace
          - name: nodered-output-volume
            mountPath: /output
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 8Gi
            cpu: 500m
      volumes:
        - name: nodered-data-store-volume
          persistentVolumeClaim:
            claimName: nodered-data-pvc
        - name: nodered-workspace-volume
          persistentVolumeClaim:
            claimName: nodered-workspace-pvc
        - name: nodered-output-volume
          persistentVolumeClaim:
            claimName: nodered-output-pvc


