apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  template:
    spec:
      containers:
      - env:
          - name: SERVICENAME
            value: nodered-service
          - name: CLUSTER_GROUP
            value: test
          - name: CLUSTER_ROLE
            value: worker
        name: CONTAINER_NAME_PLACEHOLDER
        volumeMounts:
          - mountPath: /workspace
            name: nodered-workspace-volume
          - mountPath: /output
            name: nodered-output-volume
      volumes:
        - name: nodered-workspace-volume
          persistentVolumeClaim:
            claimName: nodered-workspace-pvc
        - name: nodered-output-volume
          persistentVolumeClaim:
            claimName: nodered-output-pvc


