apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered-worker
  template:
    metadata:
      labels:
        app: nodered-worker
    spec:
      containers:
      - name: CONTAINER_NAME_PLACEHOLDER
        env:
          - name: SERVICENAME
            value: nodered-service
          - name: CLUSTER_GROUP
            value: test
          - name: CLUSTER_ROLE
            value: worker
          - name: TOPICS
            value: topic1,topic2,git
          - name: FLOW_MAX
            value: "1"