apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-jobctl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered-jobctl
  template:
    metadata:
      labels:
        app: nodered-jobctl
    spec:
      containers:
      - name: nodered-jobctl-server
        env:
          - name: JOBCTL_SERVICE_NAME
            value: nodered-jobctl-service
          - name: JOBCTL_SERVICE_PORT
            value: "18081"
          - name: CLUSTER_GROUP
            value: default
        image: jobctl
        imagePullPolicy: Never # ローカルにあるイメージを使う
        ports:
        - containerPort: 1888
        resources:
          limits:
            cpu: 500m
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
          - mountPath: /data
            name: nodered-data-store-volume
      volumes:
        - name: nodered-data-store-volume
          persistentVolumeClaim:
            claimName: nodered-data-pvc