apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - env:
          - name: TZ
            value: Asia/Tokyo
          - name: NODE_RED_ENABLE_PROJECTS
            value: "false"
        image: nodered/node-red:latest
        name: CONTAINER_NAME_PLACEHOLDER
        ports:
        - containerPort: 1880
        resources:
          limits:
            cpu: 500m
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
          - mountPath: /data
            name: nodered-data-store-volume
      volumes:
        - name: nodered-data-store-volume
          persistentVolumeClaim:
            claimName: nodered-data-pvc